version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - api-gateway-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    networks:
      - api-gateway-network
    ports:
      - "5000:5000"

  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - backend
    networks:
      - api-gateway-network

  tests:
    build: .
    container_name: api-gateway-tests
    depends_on:
      - redis
      - backend
    networks:
      - api-gateway-network
    command: ["go", "test", "-v", "./test/integration/..."]

networks:
  api-gateway-network:
    driver: bridge